env:
    - USER=travis
    - OS_TYPE=centos
    - OS_VERSION=7

sudo: false

language: go

go:
  - 1.8.3

install:
  - make deps

script:
 - GOMAXPROCS=2 make ci

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - go: 1.4.3
